### ISSUE TITLE
Updating Print blank labels Plugin to v2.1 from v2.1 Error

### ISSUE THREAD

**Issue by frogydiak** [mikejed/Rock-Plugins#3]
Hello! I tried to update to v2.1 but I am getting an error after logging to Rock Shop:

Error Updating Database An error occurred while updating the database.
Error: Cannot insert duplicate key row in object 'dbo.DefinedValue' with unique index 'IX_Guid'. The duplicate key value is (b138de05-b4b2-4c6a-a2de-079c8df55be8). Cannot insert duplicate key row in object 'dbo.BinaryFile' with unique index 'IX_Guid'. The duplicate key value is (543dab6f-f604-4b92-a03e-1469008d1059). Violation of PRIMARY KEY constraint 'PK_dbo.BinaryFileData'. Cannot insert duplicate key in object 'dbo.BinaryFileData'. The duplicate key value is (494164). Cannot insert duplicate key row in object 'dbo.AttributeValue' with unique index 'IX_AttributeIdEntityId'. The duplicate key value is (930, 1909). Cannot insert duplicate key row in object 'dbo.AttributeValue' with unique index 'IX_AttributeIdEntityId'. The duplicate key value is (931, 1909). Cannot insert duplicate key row in object 'dbo.AttributeValue' with unique index 'IX_AttributeIdEntityId'. The duplicate key value is (932, 1909). The statement has been terminated. The statement has been terminated. The statement has been terminated. The statement has been terminated. The statement has been terminated. The statement has been terminated.

Is there a way to fix this issue?

Thanks!

**Comment by mikejed** [comment]
@frogydiak v2.2 that you see in the repo was never released to the Rock Shop, and it wasn't designed to be run after v2.1. If you're trying to install v2.2 then you must be doing it by copy-and-pasting the SQL and running it directly.

**If that's also how you installed v2.1 then you have two options:**
1. Run the Uninstall process from v2.1 and then visit the Rock Shop from within your instance and install the Print Blank Labels plugin from the shop that way. That way you never have to mess with running SQL manually.
2. Skip v2.2 entirely. You can go straight from v2.1 to v3.0 if that's where you want to get.

Or, if you go to the Rock Shop > Purchases and your instance shows that you have the plugin installed already, then just update from there without running the SQL from this repo.

**Comment by frogydiak** [comment]
Hi Mike,

Sorry I mean v2.1. I don't see any Uninstall button or link under Rock Shop, all I see is Update and if I do I get that SQL error above.

Here's the screenshot of what I see under Rock Shop.

https://take.ms/UWA4Y

I also don't see Uninstall under Rock Shop > Purchases under Print blank Labels.

**Comment by mikejed** [comment]
Ok, if you installed it through the Rock shop, you’re right there’s no uninstall.

I have a suspicion of what will probably be the solution in this case but I’m not sure why it’s necessary. Let me think on it a bit. In the meantime, you can go to the code tab here in Github, click on the print blanks directory and v3.0, then just download the .exe file. There’s no actual reason you need the updated plug-in if you get it from here.

But I’ll work on getting you a solution for the actual plug-in update.

**Comment by mikejed** [comment]
@frogydiak OK, I want to check what I think may be happening. In your Power Tools > SQL Command page, would you please run the following and post back the results (this won't change anything in your database or fix the problem yet- it'll just make sure I'm on the right track).

```
DECLARE @i_ExternalApplicationDefinedTypeId AS INT = (SELECT [Id] FROM [DefinedType] WHERE [Guid] = '1fac459c-5f62-4e7c-8933-61ff9fe2dfef');
DECLARE @i_ExternalApplication_DownloadUrlAttributeId AS INT = (SELECT TOP 1 [Id] FROM [Attribute] WHERE [EntityTypeQualifierValue] = @i_ExternalApplicationDefinedTypeId AND [Key] = 'DownloadUrl');
DECLARE @i_PrintBlanksDVId AS INT = (SELECT TOP 1 [Id] FROM [DefinedValue] WHERE [Guid] = 'b138de05-b4b2-4c6a-a2de-079c8df55be8');
SELECT
    [CreatedDateTime]
    , RIGHT([Value],18) AS [Version]
FROM
    [AttributeValue]
WHERE
    [AttributeId] = @i_ExternalApplication_DownloadUrlAttributeId
    AND [EntityId] = @i_PrintBlanksDVId
```

**Comment by nateh777** [comment]
hi @mikejed, we have a client getting the exact same error when installing the update from the Rock Shop. Here is a screenshot of  the results of that SQL query.
<img width="880" alt="image" src="https://user-images.githubusercontent.com/2990519/186253359-b98cea24-ccf7-4a72-b9e9-451565ef386c.png">

**Comment by mikejed** [comment]
Thanks @nateh777 . It looks like I messed up in the first week or two of v2.1 - anyone who downloaded it during that time might be getting this issue, and unfortunately I can't fix it now through an update.

Running the following SQL (the v2.1 uninstall routine also here in Github) should allow them to update to v3 and I don't expect there to be any additional issues moving forward (if there's another update in the future 🙂)

Please try running this in Power Tools > SQL Command with "Selection Query" set to "No". It should report that 5 rows were updated. (as it turns out the third delete statement isn't needed due to the second, and that's OK). If that looks correct then change the last line to `COMMIT TRAN;` and run it again, and then the update through the Rock Shop should succeed.

```
BEGIN TRAN;
DECLARE @t_ExternalApplicationDefinedTypeGuid AS UNIQUEIDENTIFIER = '1fac459c-5f62-4e7c-8933-61ff9fe2dfef';
DECLARE @i_ExternalApplicationDefinedTypeId AS INT = (SELECT [Id] FROM [DefinedType] WHERE [Guid] = @t_ExternalApplicationDefinedTypeGuid);

DECLARE @i_ExternalApplication_IconAttributeId AS INT = (SELECT TOP 1 [Id] FROM [Attribute] WHERE [EntityTypeQualifierValue] = @i_ExternalApplicationDefinedTypeId AND [Key] = 'Icon');
DECLARE @i_ExternalApplication_VendorAttributeId AS INT = (SELECT TOP 1 [Id] FROM [Attribute] WHERE [EntityTypeQualifierValue] = @i_ExternalApplicationDefinedTypeId AND [Key] = 'Vendor');
DECLARE @i_ExternalApplication_DownloadUrlAttributeId AS INT = (SELECT TOP 1 [Id] FROM [Attribute] WHERE [EntityTypeQualifierValue] = @i_ExternalApplicationDefinedTypeId AND [Key] = 'DownloadUrl');

DECLARE @g_PrintBlanksDVGuid AS UNIQUEIDENTIFIER = 'b138de05-b4b2-4c6a-a2de-079c8df55be8';
DECLARE @i_PrintBlanksDVId AS INT = (SELECT TOP 1 [Id] FROM [DefinedValue] WHERE [Guid] = @g_PrintBlanksDVGuid);
DECLARE @g_BinaryFile_PrintBlanksGuid AS UNIQUEIDENTIFIER = '543dab6f-f604-4b92-a03e-1469008d1059';
DECLARE @i_BinaryFile_DatabaseStorageId AS INT= (SELECT TOP 1 [Id] FROM [EntityType] WHERE [Name] = 'Rock.Storage.Provider.Database');
DECLARE @i_BinaryFile_PrintBlanksIconId AS INT = (SELECT [Id] FROM [BinaryFile] WHERE [Guid] = @g_BinaryFile_PrintBlanksGuid);

DELETE FROM [DefinedValue] WHERE [Guid] = @g_PrintBlanksDVGuid;
DELETE FROM [BinaryFile] WHERE [Guid] = @g_BinaryFile_PrintBlanksGuid;
DELETE FROM [BinaryFileData] WHERE [Id] = @i_BinaryFile_PrintBlanksIconId;

DELETE FROM [AttributeValue] WHERE [EntityId] = @i_PrintBlanksDVId AND [AttributeId] = @i_ExternalApplication_IconAttributeId;
DELETE FROM [AttributeValue] WHERE [EntityId] = @i_PrintBlanksDVId AND [AttributeId] = @i_ExternalApplication_VendorAttributeId;
DELETE FROM [AttributeValue] WHERE [EntityId] = @i_PrintBlanksDVId AND [AttributeId] = @i_ExternalApplication_DownloadUrlAttributeId;

ROLLBACK TRAN;
```

**Comment by nateh777** [comment]
@mikejed thank you! That worked great. Back up to date now.

**Comment by mikejed** [comment]
@frogydiak please see [this reply to nateh777](https://github.com/mikejed/Rock-Plugins/issues/3#issuecomment-1224771052) above - I suspect this will also work for you. I'm going to add this to the troubleshooting section of the readme. My apologies for having caused these issues!
